/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:25aa8373-aa7f-4949-a5aa-8c22cb30cab9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_AEbTaB0Wg",
    "aws_user_pools_web_client_id": "6lk0nbhipidrj19fvhqmqndfvu",
    "oauth": {}
};


export default awsmobile;
